FROM mcr.microsoft.com/playwright:v1.62.1-noble@sha256:c091b21d9fae78c76e85cd4356431e9b018402f172a214fc7d7a5e9a7e29d8ac

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --global npm@12.0.1 \
    && npm ci
COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
ARG VITE_ML_API_URL
ENV VITE_ML_API_URL=$VITE_ML_API_URL

CMD ["npm", "test"]
