server {
  listen 80;
  root /usr/share/nginx/html;

  location = /index.html {
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
  }

  location ^~ /assets/ {
    try_files $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable" always;
  }

  location / {
    index index.html index.htm;
    try_files $uri /index.html =404;
    add_header Cache-Control "no-cache" always;
  }

  include /etc/nginx/extra-conf.d/*.conf;
}
