/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutApiKeysRouteImport } from './routes/_layout/api-keys'
import { Route as LayoutCategoriesRouteImport } from './routes/_layout/categories'
import { Route as LayoutCheckoutCountersRouteImport } from './routes/_layout/checkout-counters'
import { Route as LayoutIntegrationsRouteImport } from './routes/_layout/integrations'
import { Route as LayoutLabelRouteImport } from './routes/_layout/label'
import { Route as LayoutLiveSessionsRouteImport } from './routes/_layout/live-sessions'
import { Route as LayoutMlRouteImport } from './routes/_layout/ml'
import { Route as LayoutProductsRouteImport } from './routes/_layout/products'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLiveSessionsSessionIdRouteImport } from './routes/_layout/live-sessions_.$sessionId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiKeysRoute = LayoutApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCheckoutCountersRoute = LayoutCheckoutCountersRouteImport.update({
  id: '/checkout-counters',
  path: '/checkout-counters',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIntegrationsRoute = LayoutIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLabelRoute = LayoutLabelRouteImport.update({
  id: '/label',
  path: '/label',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLiveSessionsRoute = LayoutLiveSessionsRouteImport.update({
  id: '/live-sessions',
  path: '/live-sessions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMlRoute = LayoutMlRouteImport.update({
  id: '/ml',
  path: '/ml',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLiveSessionsSessionIdRoute =
  LayoutLiveSessionsSessionIdRouteImport.update({
    id: '/live-sessions_/$sessionId',
    path: '/live-sessions/$sessionId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/api-keys': typeof LayoutApiKeysRoute
  '/categories': typeof LayoutCategoriesRoute
  '/checkout-counters': typeof LayoutCheckoutCountersRoute
  '/integrations': typeof LayoutIntegrationsRoute
  '/label': typeof LayoutLabelRoute
  '/live-sessions': typeof LayoutLiveSessionsRoute
  '/ml': typeof LayoutMlRoute
  '/products': typeof LayoutProductsRoute
  '/settings': typeof LayoutSettingsRoute
  '/live-sessions/$sessionId': typeof LayoutLiveSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/api-keys': typeof LayoutApiKeysRoute
  '/categories': typeof LayoutCategoriesRoute
  '/checkout-counters': typeof LayoutCheckoutCountersRoute
  '/integrations': typeof LayoutIntegrationsRoute
  '/label': typeof LayoutLabelRoute
  '/live-sessions': typeof LayoutLiveSessionsRoute
  '/ml': typeof LayoutMlRoute
  '/products': typeof LayoutProductsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/live-sessions/$sessionId': typeof LayoutLiveSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/api-keys': typeof LayoutApiKeysRoute
  '/_layout/categories': typeof LayoutCategoriesRoute
  '/_layout/checkout-counters': typeof LayoutCheckoutCountersRoute
  '/_layout/integrations': typeof LayoutIntegrationsRoute
  '/_layout/label': typeof LayoutLabelRoute
  '/_layout/live-sessions': typeof LayoutLiveSessionsRoute
  '/_layout/ml': typeof LayoutMlRoute
  '/_layout/products': typeof LayoutProductsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/live-sessions_/$sessionId': typeof LayoutLiveSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/api-keys'
    | '/categories'
    | '/checkout-counters'
    | '/integrations'
    | '/label'
    | '/live-sessions'
    | '/ml'
    | '/products'
    | '/settings'
    | '/live-sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/api-keys'
    | '/categories'
    | '/checkout-counters'
    | '/integrations'
    | '/label'
    | '/live-sessions'
    | '/ml'
    | '/products'
    | '/settings'
    | '/'
    | '/live-sessions/$sessionId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/api-keys'
    | '/_layout/categories'
    | '/_layout/checkout-counters'
    | '/_layout/integrations'
    | '/_layout/label'
    | '/_layout/live-sessions'
    | '/_layout/ml'
    | '/_layout/products'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/live-sessions_/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-keys': {
      id: '/_layout/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof LayoutApiKeysRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checkout-counters': {
      id: '/_layout/checkout-counters'
      path: '/checkout-counters'
      fullPath: '/checkout-counters'
      preLoaderRoute: typeof LayoutCheckoutCountersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/integrations': {
      id: '/_layout/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof LayoutIntegrationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/label': {
      id: '/_layout/label'
      path: '/label'
      fullPath: '/label'
      preLoaderRoute: typeof LayoutLabelRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/live-sessions': {
      id: '/_layout/live-sessions'
      path: '/live-sessions'
      fullPath: '/live-sessions'
      preLoaderRoute: typeof LayoutLiveSessionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ml': {
      id: '/_layout/ml'
      path: '/ml'
      fullPath: '/ml'
      preLoaderRoute: typeof LayoutMlRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/live-sessions_/$sessionId': {
      id: '/_layout/live-sessions_/$sessionId'
      path: '/live-sessions/$sessionId'
      fullPath: '/live-sessions/$sessionId'
      preLoaderRoute: typeof LayoutLiveSessionsSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutApiKeysRoute: typeof LayoutApiKeysRoute
  LayoutCategoriesRoute: typeof LayoutCategoriesRoute
  LayoutCheckoutCountersRoute: typeof LayoutCheckoutCountersRoute
  LayoutIntegrationsRoute: typeof LayoutIntegrationsRoute
  LayoutLabelRoute: typeof LayoutLabelRoute
  LayoutLiveSessionsRoute: typeof LayoutLiveSessionsRoute
  LayoutMlRoute: typeof LayoutMlRoute
  LayoutProductsRoute: typeof LayoutProductsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutLiveSessionsSessionIdRoute: typeof LayoutLiveSessionsSessionIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutApiKeysRoute: LayoutApiKeysRoute,
  LayoutCategoriesRoute: LayoutCategoriesRoute,
  LayoutCheckoutCountersRoute: LayoutCheckoutCountersRoute,
  LayoutIntegrationsRoute: LayoutIntegrationsRoute,
  LayoutLabelRoute: LayoutLabelRoute,
  LayoutLiveSessionsRoute: LayoutLiveSessionsRoute,
  LayoutMlRoute: LayoutMlRoute,
  LayoutProductsRoute: LayoutProductsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutLiveSessionsSessionIdRoute: LayoutLiveSessionsSessionIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
