// This file is auto-generated by @hey-api/openapi-ts

export const AutolabelSettingsPublicSchema = {
    properties: {
        endpoint_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Endpoint Url'
        },
        max_tokens: {
            type: 'integer',
            maximum: 4096,
            minimum: 1,
            title: 'Max Tokens',
            default: 512
        },
        connect_timeout_seconds: {
            type: 'integer',
            maximum: 30,
            minimum: 1,
            title: 'Connect Timeout Seconds',
            default: 5
        },
        read_timeout_seconds: {
            type: 'integer',
            maximum: 600,
            minimum: 1,
            title: 'Read Timeout Seconds',
            default: 120
        },
        configured: {
            type: 'boolean',
            title: 'Configured'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'configured'
    ],
    title: 'AutolabelSettingsPublic'
} as const;

export const AutolabelSettingsUpdateSchema = {
    properties: {
        endpoint_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Endpoint Url'
        },
        max_tokens: {
            type: 'integer',
            maximum: 4096,
            minimum: 1,
            title: 'Max Tokens',
            default: 512
        },
        connect_timeout_seconds: {
            type: 'integer',
            maximum: 30,
            minimum: 1,
            title: 'Connect Timeout Seconds',
            default: 5
        },
        read_timeout_seconds: {
            type: 'integer',
            maximum: 600,
            minimum: 1,
            title: 'Read Timeout Seconds',
            default: 120
        }
    },
    type: 'object',
    title: 'AutolabelSettingsUpdate'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login-login_access_token'
} as const;

export const Body_products_upload_product_imageSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: [
        'file'
    ],
    title: 'Body_products-upload_product_image'
} as const;

export const CategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CategoriesPublic'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'CategoryCreate'
} as const;

export const CategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        key: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Key'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'name',
        'key',
        'id'
    ],
    title: 'CategoryPublic'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'CategoryUpdate'
} as const;

export const CheckoutCameraInfoSchema = {
    properties: {
        device_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Device Id'
        },
        label: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Label'
        },
        index: {
            type: 'integer',
            maximum: 65535,
            minimum: 0,
            title: 'Index'
        }
    },
    type: 'object',
    required: [
        'device_id',
        'label',
        'index'
    ],
    title: 'CheckoutCameraInfo'
} as const;

export const CheckoutCounterCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        password: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'name',
        'password'
    ],
    title: 'CheckoutCounterCreate'
} as const;

export const CheckoutCounterPublicSchema = {
    properties: {
        ml_mode: {
            $ref: '#/components/schemas/CheckoutMlMode',
            default: 'off'
        },
        shelf_camera_device_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shelf Camera Device Id'
        },
        scale_camera_device_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scale Camera Device Id'
        },
        language: {
            type: 'string',
            maxLength: 8,
            minLength: 2,
            title: 'Language',
            default: 'pl'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        available_cameras: {
            items: {
                $ref: '#/components/schemas/CheckoutCameraInfo'
            },
            type: 'array',
            title: 'Available Cameras'
        },
        available_cameras_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Available Cameras Updated At'
        }
    },
    type: 'object',
    required: [
        'name',
        'id'
    ],
    title: 'CheckoutCounterPublic'
} as const;

export const CheckoutCounterSelfSettingsUpdateSchema = {
    properties: {
        counter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Counter Id'
        },
        password: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Password'
        },
        ml_mode: {
            anyOf: [
                {
                    $ref: '#/components/schemas/CheckoutMlMode'
                },
                {
                    type: 'null'
                }
            ]
        },
        shelf_camera_device_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shelf Camera Device Id'
        },
        scale_camera_device_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scale Camera Device Id'
        },
        language: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 8,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        }
    },
    type: 'object',
    required: [
        'counter_id',
        'password'
    ],
    title: 'CheckoutCounterSelfSettingsUpdate'
} as const;

export const CheckoutCounterSettingsBaseSchema = {
    properties: {
        ml_mode: {
            $ref: '#/components/schemas/CheckoutMlMode',
            default: 'off'
        },
        shelf_camera_device_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shelf Camera Device Id'
        },
        scale_camera_device_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scale Camera Device Id'
        },
        language: {
            type: 'string',
            maxLength: 8,
            minLength: 2,
            title: 'Language',
            default: 'pl'
        }
    },
    type: 'object',
    title: 'CheckoutCounterSettingsBase'
} as const;

export const CheckoutCounterUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        ml_mode: {
            anyOf: [
                {
                    $ref: '#/components/schemas/CheckoutMlMode'
                },
                {
                    type: 'null'
                }
            ]
        },
        shelf_camera_device_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shelf Camera Device Id'
        },
        scale_camera_device_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scale Camera Device Id'
        },
        language: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 8,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        }
    },
    type: 'object',
    title: 'CheckoutCounterUpdate'
} as const;

export const CheckoutCountersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CheckoutCounterPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CheckoutCountersPublic'
} as const;

export const CheckoutMlModeSchema = {
    type: 'string',
    enum: [
        'off',
        'label',
        'on'
    ],
    title: 'CheckoutMlMode'
} as const;

export const CheckoutSessionCartItemSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        unit: {
            $ref: '#/components/schemas/ProductUnit'
        },
        price: {
            type: 'number',
            minimum: 0,
            title: 'Price'
        },
        quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        quantity_label: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Quantity Label'
        },
        line_total: {
            type: 'number',
            minimum: 0,
            title: 'Line Total'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    required: [
        'product_id',
        'name',
        'unit',
        'price',
        'quantity',
        'quantity_label',
        'line_total'
    ],
    title: 'CheckoutSessionCartItem'
} as const;

export const CheckoutSessionCartUpdateSchema = {
    properties: {
        counter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Counter Id'
        },
        password: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Password'
        },
        client_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Client Id'
        },
        cart: {
            items: {
                $ref: '#/components/schemas/CheckoutSessionCartItem'
            },
            type: 'array',
            title: 'Cart'
        }
    },
    type: 'object',
    required: [
        'counter_id',
        'password',
        'client_id'
    ],
    title: 'CheckoutSessionCartUpdate'
} as const;

export const CheckoutSessionConnectSchema = {
    properties: {
        available_cameras: {
            items: {
                $ref: '#/components/schemas/CheckoutCameraInfo'
            },
            type: 'array',
            maxItems: 32,
            title: 'Available Cameras'
        },
        camera_discovery_succeeded: {
            type: 'boolean',
            title: 'Camera Discovery Succeeded',
            default: true
        },
        counter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Counter Id'
        },
        password: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Password'
        },
        client_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Client Id'
        }
    },
    type: 'object',
    required: [
        'counter_id',
        'password',
        'client_id'
    ],
    title: 'CheckoutSessionConnect'
} as const;

export const CheckoutSessionPaymentSchema = {
    properties: {
        counter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Counter Id'
        },
        password: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Password'
        },
        client_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Client Id'
        }
    },
    type: 'object',
    required: [
        'counter_id',
        'password',
        'client_id'
    ],
    title: 'CheckoutSessionPayment'
} as const;

export const CheckoutSessionPaymentStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'paid'
    ],
    title: 'CheckoutSessionPaymentStatus'
} as const;

export const CheckoutSessionPublicSchema = {
    properties: {
        client_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Client Id'
        },
        closed: {
            type: 'boolean',
            title: 'Closed',
            default: false
        },
        payment_status: {
            $ref: '#/components/schemas/CheckoutSessionPaymentStatus',
            default: 'pending'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        counter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Counter Id'
        },
        cart: {
            items: {
                $ref: '#/components/schemas/CheckoutSessionCartItem'
            },
            type: 'array',
            title: 'Cart'
        },
        counter_settings: {
            $ref: '#/components/schemas/CheckoutCounterSettingsBase'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        closed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Closed At'
        }
    },
    type: 'object',
    required: [
        'client_id',
        'id',
        'counter_id',
        'cart',
        'counter_settings'
    ],
    title: 'CheckoutSessionPublic'
} as const;

export const CheckoutSessionsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CheckoutSessionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CheckoutSessionsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'title'
    ],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'title',
        'id',
        'owner_id'
    ],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'token',
        'new_password'
    ],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: [
        'email',
        'password',
        'full_name'
    ],
    title: 'PrivateUserCreate'
} as const;

export const ProductCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,8}|(?=[\\d.]{1,11}0*$)\\d{0,8}\\.\\d{0,2}0*$)'
                }
            ],
            title: 'Price'
        },
        unit: {
            $ref: '#/components/schemas/ProductUnit'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        thumbnail_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thumbnail Url'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        }
    },
    type: 'object',
    required: [
        'name',
        'price',
        'unit'
    ],
    title: 'ProductCreate'
} as const;

export const ProductPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,8}|(?=[\\d.]{1,11}0*$)\\d{0,8}\\.\\d{0,2}0*$)',
            title: 'Price'
        },
        unit: {
            $ref: '#/components/schemas/ProductUnit'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        thumbnail_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thumbnail Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        category_name: {
            type: 'string',
            title: 'Category Name'
        },
        category_key: {
            type: 'string',
            title: 'Category Key'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'name',
        'price',
        'unit',
        'id',
        'category_id',
        'category_name',
        'category_key'
    ],
    title: 'ProductPublic'
} as const;

export const ProductUnitSchema = {
    type: 'string',
    enum: [
        'kg',
        'pcs'
    ],
    title: 'ProductUnit'
} as const;

export const ProductUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,8}|(?=[\\d.]{1,11}0*$)\\d{0,8}\\.\\d{0,2}0*$)'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        unit: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ProductUnit'
                },
                {
                    type: 'null'
                }
            ]
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        }
    },
    type: 'object',
    title: 'ProductUpdate'
} as const;

export const ProductsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ProductsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'email',
        'id'
    ],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
