// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AutolabelSettingsPublic
 */
export type AutolabelSettingsPublic = {
    /**
     * Endpoint Url
     */
    endpoint_url?: string | null;
    /**
     * Max Tokens
     */
    max_tokens?: number;
    /**
     * Connect Timeout Seconds
     */
    connect_timeout_seconds?: number;
    /**
     * Read Timeout Seconds
     */
    read_timeout_seconds?: number;
    /**
     * Configured
     */
    configured: boolean;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * AutolabelSettingsUpdate
 */
export type AutolabelSettingsUpdate = {
    /**
     * Endpoint Url
     */
    endpoint_url?: string | null;
    /**
     * Max Tokens
     */
    max_tokens?: number;
    /**
     * Connect Timeout Seconds
     */
    connect_timeout_seconds?: number;
    /**
     * Read Timeout Seconds
     */
    read_timeout_seconds?: number;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_products-upload_product_image
 */
export type BodyProductsUploadProductImage = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CategoriesPublic
 */
export type CategoriesPublic = {
    /**
     * Data
     */
    data: Array<CategoryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CategoryCreate
 */
export type CategoryCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * CategoryPublic
 */
export type CategoryPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Key
     */
    key: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CategoryUpdate
 */
export type CategoryUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * CheckoutCameraInfo
 */
export type CheckoutCameraInfo = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Index
     */
    index: number;
};

/**
 * CheckoutCounterCreate
 */
export type CheckoutCounterCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * CheckoutCounterPublic
 */
export type CheckoutCounterPublic = {
    ml_mode?: CheckoutMlMode;
    /**
     * Shelf Camera Device Id
     */
    shelf_camera_device_id?: string | null;
    /**
     * Scale Camera Device Id
     */
    scale_camera_device_id?: string | null;
    /**
     * Language
     */
    language?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Available Cameras
     */
    available_cameras?: Array<CheckoutCameraInfo>;
    /**
     * Available Cameras Updated At
     */
    available_cameras_updated_at?: string | null;
};

/**
 * CheckoutCounterSelfSettingsUpdate
 */
export type CheckoutCounterSelfSettingsUpdate = {
    /**
     * Counter Id
     */
    counter_id: string;
    /**
     * Password
     */
    password: string;
    ml_mode?: CheckoutMlMode | null;
    /**
     * Shelf Camera Device Id
     */
    shelf_camera_device_id?: string | null;
    /**
     * Scale Camera Device Id
     */
    scale_camera_device_id?: string | null;
    /**
     * Language
     */
    language?: string | null;
};

/**
 * CheckoutCounterSettingsBase
 */
export type CheckoutCounterSettingsBase = {
    ml_mode?: CheckoutMlMode;
    /**
     * Shelf Camera Device Id
     */
    shelf_camera_device_id?: string | null;
    /**
     * Scale Camera Device Id
     */
    scale_camera_device_id?: string | null;
    /**
     * Language
     */
    language?: string;
};

/**
 * CheckoutCounterUpdate
 */
export type CheckoutCounterUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    ml_mode?: CheckoutMlMode | null;
    /**
     * Shelf Camera Device Id
     */
    shelf_camera_device_id?: string | null;
    /**
     * Scale Camera Device Id
     */
    scale_camera_device_id?: string | null;
    /**
     * Language
     */
    language?: string | null;
};

/**
 * CheckoutCountersPublic
 */
export type CheckoutCountersPublic = {
    /**
     * Data
     */
    data: Array<CheckoutCounterPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CheckoutMlMode
 */
export type CheckoutMlMode = 'off' | 'label' | 'on';

/**
 * CheckoutSessionCartItem
 */
export type CheckoutSessionCartItem = {
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Name
     */
    name: string;
    unit: ProductUnit;
    /**
     * Price
     */
    price: number;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Quantity Label
     */
    quantity_label: string;
    /**
     * Line Total
     */
    line_total: number;
    /**
     * Image Url
     */
    image_url?: string | null;
};

/**
 * CheckoutSessionCartUpdate
 */
export type CheckoutSessionCartUpdate = {
    /**
     * Counter Id
     */
    counter_id: string;
    /**
     * Password
     */
    password: string;
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Cart
     */
    cart?: Array<CheckoutSessionCartItem>;
};

/**
 * CheckoutSessionConnect
 */
export type CheckoutSessionConnect = {
    /**
     * Available Cameras
     */
    available_cameras?: Array<CheckoutCameraInfo>;
    /**
     * Camera Discovery Succeeded
     */
    camera_discovery_succeeded?: boolean;
    /**
     * Counter Id
     */
    counter_id: string;
    /**
     * Password
     */
    password: string;
    /**
     * Client Id
     */
    client_id: string;
};

/**
 * CheckoutSessionPayment
 */
export type CheckoutSessionPayment = {
    /**
     * Counter Id
     */
    counter_id: string;
    /**
     * Password
     */
    password: string;
    /**
     * Client Id
     */
    client_id: string;
};

/**
 * CheckoutSessionPaymentStatus
 */
export type CheckoutSessionPaymentStatus = 'pending' | 'paid';

/**
 * CheckoutSessionPublic
 */
export type CheckoutSessionPublic = {
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Closed
     */
    closed?: boolean;
    payment_status?: CheckoutSessionPaymentStatus;
    /**
     * Id
     */
    id: string;
    /**
     * Counter Id
     */
    counter_id: string;
    /**
     * Cart
     */
    cart: Array<CheckoutSessionCartItem>;
    counter_settings: CheckoutCounterSettingsBase;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Closed At
     */
    closed_at?: string | null;
};

/**
 * CheckoutSessionsPublic
 */
export type CheckoutSessionsPublic = {
    /**
     * Data
     */
    data: Array<CheckoutSessionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * LabelStudioSettingsPublic
 */
export type LabelStudioSettingsPublic = {
    /**
     * Api Key Configured
     */
    api_key_configured: boolean;
};

/**
 * LabelStudioSettingsUpdate
 */
export type LabelStudioSettingsUpdate = {
    /**
     * Api Key
     */
    api_key: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Price
     */
    price: number | string;
    unit: ProductUnit;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Thumbnail Url
     */
    thumbnail_url?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
};

/**
 * ProductPublic
 */
export type ProductPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Price
     */
    price: string;
    unit: ProductUnit;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Thumbnail Url
     */
    thumbnail_url?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Category Id
     */
    category_id: string;
    /**
     * Category Name
     */
    category_name: string;
    /**
     * Category Key
     */
    category_key: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ProductUnit
 */
export type ProductUnit = 'kg' | 'pcs';

/**
 * ProductUpdate
 */
export type ProductUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Price
     */
    price?: number | string | null;
    unit?: ProductUnit | null;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
};

/**
 * ProductsPublic
 */
export type ProductsPublic = {
    /**
     * Data
     */
    data: Array<ProductPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersReadLabelStudioSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/label-studio';
};

export type UsersReadLabelStudioSettingsResponses = {
    /**
     * Successful Response
     */
    200: LabelStudioSettingsPublic;
};

export type UsersReadLabelStudioSettingsResponse = UsersReadLabelStudioSettingsResponses[keyof UsersReadLabelStudioSettingsResponses];

export type UsersUpdateLabelStudioSettingsData = {
    body: LabelStudioSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/label-studio';
};

export type UsersUpdateLabelStudioSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateLabelStudioSettingsError = UsersUpdateLabelStudioSettingsErrors[keyof UsersUpdateLabelStudioSettingsErrors];

export type UsersUpdateLabelStudioSettingsResponses = {
    /**
     * Successful Response
     */
    200: LabelStudioSettingsPublic;
};

export type UsersUpdateLabelStudioSettingsResponse = UsersUpdateLabelStudioSettingsResponses[keyof UsersUpdateLabelStudioSettingsResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type ItemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type ItemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors];

export type ItemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses];

export type ItemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type ItemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors];

export type ItemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses];

export type ItemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors];

export type ItemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses];

export type ItemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors];

export type ItemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses];

export type ProductsReadProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/products/';
};

export type ProductsReadProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsReadProductsError = ProductsReadProductsErrors[keyof ProductsReadProductsErrors];

export type ProductsReadProductsResponses = {
    /**
     * Successful Response
     */
    200: ProductsPublic;
};

export type ProductsReadProductsResponse = ProductsReadProductsResponses[keyof ProductsReadProductsResponses];

export type ProductsCreateProductData = {
    body: ProductCreate;
    path?: never;
    query?: never;
    url: '/api/v1/products/';
};

export type ProductsCreateProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsCreateProductError = ProductsCreateProductErrors[keyof ProductsCreateProductErrors];

export type ProductsCreateProductResponses = {
    /**
     * Successful Response
     */
    200: ProductPublic;
};

export type ProductsCreateProductResponse = ProductsCreateProductResponses[keyof ProductsCreateProductResponses];

export type ProductsDeleteProductData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/products/{id}';
};

export type ProductsDeleteProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsDeleteProductError = ProductsDeleteProductErrors[keyof ProductsDeleteProductErrors];

export type ProductsDeleteProductResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProductsDeleteProductResponse = ProductsDeleteProductResponses[keyof ProductsDeleteProductResponses];

export type ProductsReadProductData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/products/{id}';
};

export type ProductsReadProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsReadProductError = ProductsReadProductErrors[keyof ProductsReadProductErrors];

export type ProductsReadProductResponses = {
    /**
     * Successful Response
     */
    200: ProductPublic;
};

export type ProductsReadProductResponse = ProductsReadProductResponses[keyof ProductsReadProductResponses];

export type ProductsUpdateProductData = {
    body: ProductUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/products/{id}';
};

export type ProductsUpdateProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsUpdateProductError = ProductsUpdateProductErrors[keyof ProductsUpdateProductErrors];

export type ProductsUpdateProductResponses = {
    /**
     * Successful Response
     */
    200: ProductPublic;
};

export type ProductsUpdateProductResponse = ProductsUpdateProductResponses[keyof ProductsUpdateProductResponses];

export type ProductsUploadProductImageData = {
    body: BodyProductsUploadProductImage;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/products/{id}/image';
};

export type ProductsUploadProductImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsUploadProductImageError = ProductsUploadProductImageErrors[keyof ProductsUploadProductImageErrors];

export type ProductsUploadProductImageResponses = {
    /**
     * Successful Response
     */
    200: ProductPublic;
};

export type ProductsUploadProductImageResponse = ProductsUploadProductImageResponses[keyof ProductsUploadProductImageResponses];

export type SystemSettingsReadAutolabelSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system-settings/autolabel';
};

export type SystemSettingsReadAutolabelSettingsResponses = {
    /**
     * Successful Response
     */
    200: AutolabelSettingsPublic;
};

export type SystemSettingsReadAutolabelSettingsResponse = SystemSettingsReadAutolabelSettingsResponses[keyof SystemSettingsReadAutolabelSettingsResponses];

export type SystemSettingsUpdateAutolabelSettingsData = {
    body: AutolabelSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/system-settings/autolabel';
};

export type SystemSettingsUpdateAutolabelSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SystemSettingsUpdateAutolabelSettingsError = SystemSettingsUpdateAutolabelSettingsErrors[keyof SystemSettingsUpdateAutolabelSettingsErrors];

export type SystemSettingsUpdateAutolabelSettingsResponses = {
    /**
     * Successful Response
     */
    200: AutolabelSettingsPublic;
};

export type SystemSettingsUpdateAutolabelSettingsResponse = SystemSettingsUpdateAutolabelSettingsResponses[keyof SystemSettingsUpdateAutolabelSettingsResponses];

export type CategoriesReadCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/categories/';
};

export type CategoriesReadCategoriesResponses = {
    /**
     * Successful Response
     */
    200: CategoriesPublic;
};

export type CategoriesReadCategoriesResponse = CategoriesReadCategoriesResponses[keyof CategoriesReadCategoriesResponses];

export type CategoriesCreateCategoryData = {
    body: CategoryCreate;
    path?: never;
    query?: never;
    url: '/api/v1/categories/';
};

export type CategoriesCreateCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesCreateCategoryError = CategoriesCreateCategoryErrors[keyof CategoriesCreateCategoryErrors];

export type CategoriesCreateCategoryResponses = {
    /**
     * Successful Response
     */
    200: CategoryPublic;
};

export type CategoriesCreateCategoryResponse = CategoriesCreateCategoryResponses[keyof CategoriesCreateCategoryResponses];

export type CategoriesDeleteCategoryData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/categories/{id}';
};

export type CategoriesDeleteCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesDeleteCategoryError = CategoriesDeleteCategoryErrors[keyof CategoriesDeleteCategoryErrors];

export type CategoriesDeleteCategoryResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CategoriesDeleteCategoryResponse = CategoriesDeleteCategoryResponses[keyof CategoriesDeleteCategoryResponses];

export type CategoriesUpdateCategoryData = {
    body: CategoryUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/categories/{id}';
};

export type CategoriesUpdateCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesUpdateCategoryError = CategoriesUpdateCategoryErrors[keyof CategoriesUpdateCategoryErrors];

export type CategoriesUpdateCategoryResponses = {
    /**
     * Successful Response
     */
    200: CategoryPublic;
};

export type CategoriesUpdateCategoryResponse = CategoriesUpdateCategoryResponses[keyof CategoriesUpdateCategoryResponses];

export type CheckoutCountersReadCheckoutCountersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/checkout-counters/';
};

export type CheckoutCountersReadCheckoutCountersResponses = {
    /**
     * Successful Response
     */
    200: CheckoutCountersPublic;
};

export type CheckoutCountersReadCheckoutCountersResponse = CheckoutCountersReadCheckoutCountersResponses[keyof CheckoutCountersReadCheckoutCountersResponses];

export type CheckoutCountersCreateCheckoutCounterData = {
    body: CheckoutCounterCreate;
    path?: never;
    query?: never;
    url: '/api/v1/checkout-counters/';
};

export type CheckoutCountersCreateCheckoutCounterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckoutCountersCreateCheckoutCounterError = CheckoutCountersCreateCheckoutCounterErrors[keyof CheckoutCountersCreateCheckoutCounterErrors];

export type CheckoutCountersCreateCheckoutCounterResponses = {
    /**
     * Successful Response
     */
    200: CheckoutCounterPublic;
};

export type CheckoutCountersCreateCheckoutCounterResponse = CheckoutCountersCreateCheckoutCounterResponses[keyof CheckoutCountersCreateCheckoutCounterResponses];

export type CheckoutCountersDeleteCheckoutCounterData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/checkout-counters/{id}';
};

export type CheckoutCountersDeleteCheckoutCounterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckoutCountersDeleteCheckoutCounterError = CheckoutCountersDeleteCheckoutCounterErrors[keyof CheckoutCountersDeleteCheckoutCounterErrors];

export type CheckoutCountersDeleteCheckoutCounterResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CheckoutCountersDeleteCheckoutCounterResponse = CheckoutCountersDeleteCheckoutCounterResponses[keyof CheckoutCountersDeleteCheckoutCounterResponses];

export type CheckoutCountersUpdateCheckoutCounterData = {
    body: CheckoutCounterUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/checkout-counters/{id}';
};

export type CheckoutCountersUpdateCheckoutCounterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckoutCountersUpdateCheckoutCounterError = CheckoutCountersUpdateCheckoutCounterErrors[keyof CheckoutCountersUpdateCheckoutCounterErrors];

export type CheckoutCountersUpdateCheckoutCounterResponses = {
    /**
     * Successful Response
     */
    200: CheckoutCounterPublic;
};

export type CheckoutCountersUpdateCheckoutCounterResponse = CheckoutCountersUpdateCheckoutCounterResponses[keyof CheckoutCountersUpdateCheckoutCounterResponses];

export type CheckoutCountersUpdateSelfCheckoutCounterSettingsData = {
    body: CheckoutCounterSelfSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/checkout-counters/me/settings';
};

export type CheckoutCountersUpdateSelfCheckoutCounterSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckoutCountersUpdateSelfCheckoutCounterSettingsError = CheckoutCountersUpdateSelfCheckoutCounterSettingsErrors[keyof CheckoutCountersUpdateSelfCheckoutCounterSettingsErrors];

export type CheckoutCountersUpdateSelfCheckoutCounterSettingsResponses = {
    /**
     * Successful Response
     */
    200: CheckoutCounterPublic;
};

export type CheckoutCountersUpdateSelfCheckoutCounterSettingsResponse = CheckoutCountersUpdateSelfCheckoutCounterSettingsResponses[keyof CheckoutCountersUpdateSelfCheckoutCounterSettingsResponses];

export type CheckoutSessionsListActiveCheckoutSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/checkout-sessions/active';
};

export type CheckoutSessionsListActiveCheckoutSessionsResponses = {
    /**
     * Successful Response
     */
    200: CheckoutSessionsPublic;
};

export type CheckoutSessionsListActiveCheckoutSessionsResponse = CheckoutSessionsListActiveCheckoutSessionsResponses[keyof CheckoutSessionsListActiveCheckoutSessionsResponses];

export type CheckoutSessionsConnectCheckoutSessionData = {
    body: CheckoutSessionConnect;
    path?: never;
    query?: never;
    url: '/api/v1/checkout-sessions/connect';
};

export type CheckoutSessionsConnectCheckoutSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckoutSessionsConnectCheckoutSessionError = CheckoutSessionsConnectCheckoutSessionErrors[keyof CheckoutSessionsConnectCheckoutSessionErrors];

export type CheckoutSessionsConnectCheckoutSessionResponses = {
    /**
     * Successful Response
     */
    200: CheckoutSessionPublic;
};

export type CheckoutSessionsConnectCheckoutSessionResponse = CheckoutSessionsConnectCheckoutSessionResponses[keyof CheckoutSessionsConnectCheckoutSessionResponses];

export type CheckoutSessionsUpdateCheckoutSessionCartData = {
    body: CheckoutSessionCartUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/checkout-sessions/{id}/cart';
};

export type CheckoutSessionsUpdateCheckoutSessionCartErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckoutSessionsUpdateCheckoutSessionCartError = CheckoutSessionsUpdateCheckoutSessionCartErrors[keyof CheckoutSessionsUpdateCheckoutSessionCartErrors];

export type CheckoutSessionsUpdateCheckoutSessionCartResponses = {
    /**
     * Successful Response
     */
    200: CheckoutSessionPublic;
};

export type CheckoutSessionsUpdateCheckoutSessionCartResponse = CheckoutSessionsUpdateCheckoutSessionCartResponses[keyof CheckoutSessionsUpdateCheckoutSessionCartResponses];

export type CheckoutSessionsPayCheckoutSessionData = {
    body: CheckoutSessionPayment;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/checkout-sessions/{id}/pay';
};

export type CheckoutSessionsPayCheckoutSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckoutSessionsPayCheckoutSessionError = CheckoutSessionsPayCheckoutSessionErrors[keyof CheckoutSessionsPayCheckoutSessionErrors];

export type CheckoutSessionsPayCheckoutSessionResponses = {
    /**
     * Successful Response
     */
    200: CheckoutSessionPublic;
};

export type CheckoutSessionsPayCheckoutSessionResponse = CheckoutSessionsPayCheckoutSessionResponses[keyof CheckoutSessionsPayCheckoutSessionResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];
