// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_products_upload_product_image = {
    file: (Blob | File);
};

export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

export type CategoryCreate = {
    name: string;
};

export type CategoryPublic = {
    name: string;
    key: string;
    id: string;
    created_at?: (string | null);
};

export type CategoryUpdate = {
    name?: (string | null);
};

export type CheckoutCounterCreate = {
    name: string;
    password: string;
};

export type CheckoutMlMode = 'off' | 'label' | 'on';

export type CheckoutCounterPublic = {
    name: string;
    id: string;
    ml_mode: CheckoutMlMode;
    shelf_camera_device_id?: (string | null);
    scale_camera_device_id?: (string | null);
    language: string;
    created_at?: (string | null);
};

export type CheckoutCountersPublic = {
    data: Array<CheckoutCounterPublic>;
    count: number;
};

export type CheckoutCounterUpdate = {
    name?: (string | null);
    password?: (string | null);
    ml_mode?: (CheckoutMlMode | null);
    shelf_camera_device_id?: (string | null);
    scale_camera_device_id?: (string | null);
    language?: (string | null);
};

export type CheckoutSessionCartItem = {
    product_id: string;
    name: string;
    unit: ProductUnit;
    price: number;
    quantity: number;
    quantity_label: string;
    line_total: number;
    image_url?: (string | null);
};

export type CheckoutSessionCartUpdate = {
    counter_id: string;
    password: string;
    client_id: string;
    cart?: Array<CheckoutSessionCartItem>;
};

export type CheckoutSessionConnect = {
    counter_id: string;
    password: string;
    client_id: string;
};

export type CheckoutSessionPayment = {
    counter_id: string;
    password: string;
    client_id: string;
};

export type CheckoutSessionPaymentStatus = 'pending' | 'paid';

export type CheckoutSessionCounterSettings = {
    ml_mode: CheckoutMlMode;
    shelf_camera_device_id?: (string | null);
    scale_camera_device_id?: (string | null);
    language: string;
};

export type CheckoutSessionPublic = {
    client_id: string;
    closed?: boolean;
    payment_status?: CheckoutSessionPaymentStatus;
    id: string;
    counter_id: string;
    cart: Array<CheckoutSessionCartItem>;
    counter_settings?: (CheckoutSessionCounterSettings | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    closed_at?: (string | null);
};

export type CheckoutSessionsPublic = {
    data: Array<CheckoutSessionPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductCreate = {
    name: string;
    price: (number | string);
    unit: ProductUnit;
    image_url?: (string | null);
    category_id?: (string | null);
};

export type ProductPublic = {
    name: string;
    price: string;
    unit: ProductUnit;
    image_url?: (string | null);
    id: string;
    category_id: string;
    category_name: string;
    category_key: string;
    created_at?: (string | null);
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ProductUnit = 'kg' | 'pcs';

export type ProductUpdate = {
    name?: (string | null);
    price?: (number | string | null);
    unit?: (ProductUnit | null);
    image_url?: (string | null);
    category_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type CategoriesReadCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    id: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    id: string;
};

export type CategoriesDeleteCategoryResponse = (Message);

export type CheckoutCountersReadCheckoutCountersResponse = (CheckoutCountersPublic);

export type CheckoutCountersCreateCheckoutCounterData = {
    requestBody: CheckoutCounterCreate;
};

export type CheckoutCountersCreateCheckoutCounterResponse = (CheckoutCounterPublic);

export type CheckoutCountersUpdateCheckoutCounterData = {
    id: string;
    requestBody: CheckoutCounterUpdate;
};

export type CheckoutCountersUpdateCheckoutCounterResponse = (CheckoutCounterPublic);

export type CheckoutCountersDeleteCheckoutCounterData = {
    id: string;
};

export type CheckoutCountersDeleteCheckoutCounterResponse = (Message);

export type CheckoutSessionsReadActiveCheckoutSessionsResponse = (CheckoutSessionsPublic);

export type CheckoutSessionsConnectCheckoutSessionData = {
    requestBody: CheckoutSessionConnect;
};

export type CheckoutSessionsConnectCheckoutSessionResponse = (CheckoutSessionPublic);

export type CheckoutSessionsUpdateCheckoutSessionCartData = {
    id: string;
    requestBody: CheckoutSessionCartUpdate;
};

export type CheckoutSessionsUpdateCheckoutSessionCartResponse = (CheckoutSessionPublic);

export type CheckoutSessionsPayCheckoutSessionData = {
    id: string;
    requestBody: CheckoutSessionPayment;
};

export type CheckoutSessionsPayCheckoutSessionResponse = (CheckoutSessionPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadProductsData = {
    limit?: number;
    skip?: number;
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsReadProductData = {
    id: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    id: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    id: string;
};

export type ProductsDeleteProductResponse = (Message);

export type ProductsUploadProductImageData = {
    formData: Body_products_upload_product_image;
    id: string;
};

export type ProductsUploadProductImageResponse = (ProductPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);